name: Convert Chemical SVGs

on:
  push:
    branches: [ main ]
    paths:
      - '*.svg'
  workflow_dispatch:

jobs:
  convert-svgs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install lxml
        
    - name: Convert SVGs
      run: |
        python chem_svg_converter.py -i chemical-structures -o chemical-structures
      
    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add chemical-structures/*.svg
        git commit -m "Update SVGs with theme support" || echo "No changes to commit"
        git push
